import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

test('settings transfer remains reachable on a short desktop viewport', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.goto('/settings?section=runtime');
  const section = page.getByRole('complementary', { name: 'Settings sections' }).getByRole('button', { name: 'Import / Export Move selected settings', exact: true });
  await section.click();
  await expect(page.getByRole('heading', { name: 'Move your settings', exact: true })).toBeVisible();
  const buttonBounds = await section.boundingBox();
  const footerBounds = await page.getByRole('contentinfo').boundingBox();
  expect(buttonBounds.y + buttonBounds.height).toBeLessThanOrEqual(footerBounds.y + 1);
  await page.getByRole('button', { name: 'Choose settings to export', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Export settings', exact: true });
  const runtime = dialog.getByRole('tab', { name: /^Runtime / });
  await runtime.click();
  await runtime.press('ArrowRight');
  await expect(dialog.getByRole('tab', { name: /^Services / })).toBeFocused();
  await expect(dialog.getByRole('tab', { name: /^Services / })).toHaveAttribute('aria-selected', 'true');
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
});

test('settings export keeps selections across tabs and downloads only selected items', async ({ page }) => {
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/settings?section=import-export');
  await expect(page).toHaveTitle('Q Studio');
  await page.getByRole('button', { name: 'Choose settings to export', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Export settings', exact: true });
  await expect(dialog.getByRole('button', { name: 'Export file', exact: true })).toBeDisabled();
  await dialog.getByRole('checkbox', { name: /^Default chat model / }).check();
  await dialog.getByRole('tab', { name: /^Runtime / }).click();
  await dialog.getByRole('checkbox', { name: /^Maximum parallel agents / }).check();
  await dialog.getByRole('tab', { name: /^Models / }).click();
  await expect(dialog.getByRole('checkbox', { name: /^Default chat model / })).toBeChecked();
  await expect(dialog.getByText('2 selected across all tabs', { exact: true })).toBeVisible();
  const downloadPromise = page.waitForEvent('download');
  await dialog.getByRole('button', { name: 'Export file', exact: true }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe('q-settings.json');
  const bundle = JSON.parse(await readFile(await download.path(), 'utf8'));
  expect(bundle.format).toBe('q-settings');
  expect(bundle.version).toBe(1);
  expect(bundle.scope).toBe('global');
  expect(Object.keys(bundle.sections)).toEqual(['models', 'runtime']);
  expect(Object.keys(bundle.sections.models)).toEqual(['default']);
  expect(Object.keys(bundle.sections.runtime)).toEqual(['parallel-agents']);
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('status')).toContainText('Exported 2 settings');
  expect(errors).toEqual([]);
});

test('settings import compares values, reviews changes, and preserves unselected settings', async ({ page, request }) => {
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const before = await (await request.get('/api/v1/settings/transfer')).json();
  const afterParallel = before.sections.runtime['parallel-agents'] === 6 ? 5 : 6;
  const bundle = structuredClone(before);
  bundle.sections.runtime['parallel-agents'] = afterParallel;
  bundle.sections.runtime['system-prompt'] = 'This unselected prompt must not be imported.';
  await page.goto('/settings?section=import-export');
  await page.getByRole('button', { name: 'Choose settings to import', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Import settings', exact: true });
  await expect(dialog.locator('input[type=file]')).toBeEnabled();
  await dialog.locator('input[type=file]').setInputFiles({ name: 'selected-settings.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(bundle)) });
  await dialog.getByRole('tab', { name: /^Runtime / }).click();
  await dialog.getByRole('checkbox', { name: /^Maximum parallel agents / }).check();
  const item = dialog.getByRole('article').filter({ hasText: 'Maximum parallel agents' });
  await item.getByText('Compare values', { exact: true }).click();
  await expect(item.getByRole('heading', { name: 'Current', exact: true })).toBeVisible();
  await expect(item.getByRole('heading', { name: 'Incoming', exact: true })).toBeVisible();
  await dialog.getByRole('button', { name: 'Review selection', exact: true }).click();
  await expect(dialog.getByText('Selection reviewed', { exact: true })).toBeVisible();
  await expect(item.getByText('Replace', { exact: true })).toBeVisible();
  await expect(dialog.getByText('0 added · 1 replaced · 0 unchanged', { exact: true })).toBeVisible();
  expect(await (await request.get('/api/v1/settings/transfer')).json()).toEqual(before);
  await page.screenshot({ path: join(tmpdir(), 'q-settings-import-review.png') });
  await dialog.getByRole('button', { name: 'Import selected', exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('status')).toContainText('Imported 1 settings');
  const after = await (await request.get('/api/v1/settings/transfer')).json();
  const expected = structuredClone(before);
  expected.sections.runtime['parallel-agents'] = afterParallel;
  expect(after).toEqual(expected);
  await page.getByRole('button', { name: 'Runtime Execution, context, and storage', exact: true }).click();
  await expect(page.getByRole('spinbutton', { name: /Maximum parallel agents/ })).toHaveValue(String(afterParallel));
  // Restore the fixture so other settings flows start from their own defaults.
  const restored = await request.post('/api/v1/settings/transfer/import', { data: { format: 'q-settings', version: 1, scope: 'global', sections: { runtime: { 'parallel-agents': before.sections.runtime['parallel-agents'] } } } });
  expect(restored.ok()).toBe(true);
  expect(errors).toEqual([]);
});

test('settings transfer fits mobile and rejects unsupported files before review', async ({ page }) => {
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/settings?section=import-export');
  await page.getByRole('button', { name: 'Choose settings to import', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Import settings', exact: true });
  await expect(dialog.locator('input[type=file]')).toBeEnabled();
  await dialog.locator('input[type=file]').setInputFiles({ name: 'unsupported.json', mimeType: 'application/json', buffer: Buffer.from('{"format":"q-settings","version":999,"scope":"global","sections":{}}') });
  await expect(dialog.getByRole('alert')).toContainText('version 1');
  await expect(dialog.getByRole('button', { name: 'Review selection', exact: true })).toBeDisabled();
  await expect(dialog.getByRole('button', { name: 'Cancel', exact: true })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('button', { name: 'Choose settings to export', exact: true }).click();
  const exportDialog = page.getByRole('dialog', { name: 'Export settings', exact: true });
  await exportDialog.getByRole('tab', { name: /^Runtime / }).click();
  await exportDialog.getByRole('checkbox', { name: /^Maximum parallel agents / }).check();
  await expect(exportDialog.getByRole('button', { name: 'Export file', exact: true })).toBeInViewport();
  await page.screenshot({ path: join(tmpdir(), 'q-settings-export-mobile.png') });
  await page.keyboard.press('Escape');
  await expect(exportDialog).not.toBeVisible();
  expect(errors).toEqual([]);
});
